apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}

    {{- with .Values.service }} # with block
    {{- if .nodePort }} # if block
    nodePort: {{ .nodePort }}
    {{- end }} # End of If
    {{- end }} # End of with